"""Main browser pipeline coordinator."""

from __future__ import annotations

from dataclasses import dataclass
from typing import List

from network.http_client import HTTPClient
from network.url_parser import URLParseError
from parser.css_parser import CSSParser, CSSRule
from parser.dom_tree import DOMElement
from parser.html_parser import HTMLParser
from renderer.layout_engine import LayoutBox, LayoutEngine
from renderer.render_tree import RenderNode, RenderTreeBuilder
from storage.history import HistoryManager
from utils.logger import get_logger


@dataclass
class NavigationResult:
    """Outputs generated by one navigation."""

    final_url: str
    status_code: int
    dom_root: DOMElement
    css_rules: List[CSSRule]
    render_root: RenderNode
    layout_root: LayoutBox
    response_text: str
    page_title: str
    response_size_bytes: int


class BrowserEngine:
    """Coordinates parsing, networking, rendering and history updates."""

    def __init__(self, history_manager: HistoryManager | None = None) -> None:
        """Initialize all pipeline components."""

        self.http_client = HTTPClient()
        self.html_parser = HTMLParser()
        self.css_parser = CSSParser()
        self.render_tree_builder = RenderTreeBuilder(self.css_parser)
        self.layout_engine = LayoutEngine()
        self.history = history_manager or HistoryManager()
        self.logger = get_logger("engine.browser_engine")
        self._last_result: NavigationResult | None = None

    def navigate(
        self,
        url: str,
        viewport_width: int = 1024,
        record_history: bool = True,
    ) -> NavigationResult:
        """Run full pipeline: URL parse -> fetch -> parse -> render -> layout."""

        normalized_url = self._normalize_url(url)
        response = self.http_client.fetch(normalized_url, method="GET")
        return self._build_result(
            final_url=self._build_final_url(response.url),
            html_text=response.text,
            status_code=response.status_code,
            viewport_width=viewport_width,
            record_history=record_history,
            response_size_bytes=len(response.body),
        )

    def render_html(
        self,
        url: str,
        html_text: str,
        viewport_width: int = 1024,
        page_title: str = "",
        record_history: bool = False,
        response_size_bytes: int | None = None,
    ) -> NavigationResult:
        """Render supplied HTML without performing a network fetch."""

        if response_size_bytes is None:
            response_size_bytes = len(html_text.encode("utf-8"))

        return self._build_result(
            final_url=url,
            html_text=html_text,
            status_code=200,
            viewport_width=viewport_width,
            record_history=record_history,
            page_title=page_title,
            response_size_bytes=response_size_bytes,
        )

    def _build_result(
        self,
        final_url: str,
        html_text: str,
        status_code: int,
        viewport_width: int,
        record_history: bool,
        response_size_bytes: int,
        page_title: str = "",
    ) -> NavigationResult:
        """Run the shared parse/render/layout pipeline for HTML text."""

        dom_root = self.html_parser.parse(html_text)
        css_text = self._collect_css(dom_root)
        css_rules = self.css_parser.parse(css_text)
        render_root = self.render_tree_builder.build(dom_root, css_rules)
        layout_root = self.layout_engine.layout(render_root, viewport_width=viewport_width)
        resolved_title = page_title or self._extract_title(dom_root)

        if record_history:
            self.history.visit(final_url)

        result = NavigationResult(
            final_url=final_url,
            status_code=status_code,
            dom_root=dom_root,
            css_rules=css_rules,
            render_root=render_root,
            layout_root=layout_root,
            response_text=html_text,
            page_title=resolved_title,
            response_size_bytes=response_size_bytes,
        )
        self._last_result = result
        self.logger.info("Navigation complete for %s", final_url)
        return result

    def _normalize_url(self, url: str) -> str:
        """Normalize user input into an absolute HTTP URL."""

        cleaned = url.strip()
        if not cleaned:
            raise URLParseError("URL cannot be empty")
        if "://" not in cleaned:
            cleaned = f"http://{cleaned}"
        return cleaned

    def _collect_css(self, dom_root: DOMElement) -> str:
        """Collect parser-extracted style blocks and inline style attributes."""

        style_text = "\n".join(self.html_parser.extracted_style_blocks)

        for node in dom_root.getElementsByTagName("*"):
            inline = node.attributes.get("style")
            if inline:
                selector = self._selector_for_node(node)
                style_text += f"\n{selector}{{{inline}}}"
        return style_text

    def _selector_for_node(self, node: object) -> str:
        """Create a simple selector targeting one node for inline style fallback."""

        tag_name = getattr(node, "tag_name", "div")
        attributes = getattr(node, "attributes", {})
        if isinstance(attributes, dict) and attributes.get("id"):
            return f"#{attributes['id']}"
        if isinstance(attributes, dict) and attributes.get("class"):
            first_class = attributes["class"].split()[0]
            return f".{first_class}"
        return str(tag_name)

    def _extract_title(self, dom_root: DOMElement) -> str:
        """Extract document title text from the DOM tree."""

        title_nodes = dom_root.getElementsByTagName("title")
        if not title_nodes:
            return ""
        title_node = title_nodes[0]
        parts: list[str] = []
        for child in title_node.children:
            if child.tag_name == "#text" and child.text_content.strip():
                parts.append(child.text_content.strip())
        return " ".join(parts).strip()

    def _build_final_url(self, parsed_url: object) -> str:
        """Build canonical final URL string from parsed URL parts."""

        scheme = getattr(parsed_url, "scheme", "http")
        host = getattr(parsed_url, "host", "")
        port = int(getattr(parsed_url, "port", 80))
        path = getattr(parsed_url, "path", "/") or "/"
        query = getattr(parsed_url, "query", "")
        fragment = getattr(parsed_url, "fragment", "")

        default_port = 443 if scheme == "https" else 80
        authority = host if port == default_port else f"{host}:{port}"

        final_url = f"{scheme}://{authority}{path}"
        if query:
            final_url += f"?{query}"
        if fragment:
            final_url += f"#{fragment}"
        return final_url
